root: true
env:
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: "*.ts"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: "./tsconfig.json"
    plugins:
      - "@typescript-eslint"
      - "prettier"
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:prettier/recommended"
  - files: "*.(test|spec).ts"
    env:
      jest: true
    parserOptions:
      project: "./tsconfig.json"
    extends:
      - "plugin:jest/recommended"
      - "plugin:jest/style"
    rules:
      "jest/expect-expect": "error"
      "jest/no-disabled-tests": "warn"
      "jest/no-focused-tests": "error"
      "jest/no-identical-title": "error"
      "jest/prefer-to-have-length": "warn"
      "jest/valid-expect": "error"
