root: true
env:
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: "*.ts"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: "./tsconfig.json"
    plugins:
      - "@typescript-eslint"
      - "prettier"
      - "asteroide"
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:prettier/recommended"
      - "plugin:asteroide/recommended"
