root: true
env:
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: "*.ts"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: "./tsconfig.json"
    plugins:
      - "@typescript-eslint"
      - "prettier"
      - "asteroide"
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:prettier/recommended"
      - "plugin:asteroide/recommended"
  - files:
      - "*.spec.ts"
      - "*.e2e-spec.ts"
    env:
      jest: true
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:jest/recommended"
      - "plugin:jest/style"
      - "plugin:prettier/recommended"
    parserOptions:
      project: "./tsconfig.spec.json"
