name: dependency-review
on:
  pull_request:
    branches:
      - master
      - canary
permissions:
  contents: read
  pull-requests: write
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run dependency review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
